workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.vijayguhan.revozen"
      node: 22.12.0 # Updated to meet React Native 0.76.9 requirements
    triggering:
      events:
          - push
          - tag
          - pull_request
      branch_patterns:
          - pattern: develop
            include: true
            source: true
    scripts:
      - name: Install dependencies
        script: |
          # Use npx expo instead of global expo-cli
          npm install -g yarn
          yarn install
          npx expo install --fix # This will install compatible versions
      - name: Verify expo is installed
        script: |
          yarn list expo || (echo "Expo is not installed!" && exit 1)
      - name: Eject app from Expo
        script: |
          npx expo prebuild
      - name: Check and move build.gradle if needed
        script: |
          if [ -f ./support-files/build.gradle ]; then
            mv ./support-files/build.gradle android/app
          else
            echo "No build.gradle found in ./support-files, skipping move"
          fi
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
        - android/app/build/outputs/**/*.apk
